---
abstract: 'module for querying multiple MySQL databases in parallel'
author:
  - 'John Gravatt <gravattj@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MySQL-QueryMulti
no_index:
  directory:
    - t
    - inc
requires:
  DBD::mysql: 4.019
  DBI: 1.6
  Math::BigInt: 1.994
  Math::Complex: 1.56
  Moose: 2.0403
  SQL::Statement: 1.33
  Term::ReadLine: 1.07
  Test::More: 0
  Text::ASCIITable: 0.18
  Time::HiRes: 0
  namespace::autoclean: 0.13
version: 0.08
